const langARR = {
	"unit" : {
		"ru" : "Заметки",
		"en" : "Notes",
		"ua" : "Нотатки",
		"fr" : "Remarques",
		"de" : "Anmerkungen",
		"pl" : "Uwagi",
	},
	"title_all" : {
		"ru" : "Создание заметки",
		"en" : "Create a note",
		"ua" : "Створення нотатки",
		"fr" : "Créer une note",
		"de" : "Erstellen Sie eine Notiz",
		"pl" : "Utwórz notatkę",
	},
	"title_note" : {
		"ru" : "Заметка",
		"en" : "Note",
		"ua" : "Нотатка",
		"fr" : "La note",
		"de" : "Die Notiz",
		"pl" : "Notatka",
	},
	"placeholder" : {
		"ru" : "Введите текст заметки",
		"en" : "Enter note text",
		"ua" : "Введіть текст нотатки",
		"fr" : "Saisir le texte de la note",
		"de" : "Notiztext eingeben",
		"pl" : "Wpisz tekst notatki",
	},
	"save" : {
		"ru" : "Сохранить",
		"en" : "Save",
		"ua" : "Зберегти",
		"fr" : "Sauver",
		"de" : "Speichern",
		"pl" : "Ratować",
	},
	"open" : {
		"ru" : "Открыть",
		"en" : "Open",
		"ua" : "Відчинити",
		"fr" : "Ouvrir",
		"de" : "Offen",
		"pl" : "Otwarty",
	},
}